appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QshF8P9FaFHK3TNugE+B6wokbQIh0UChqhB2q0TKLPB4xtbi2X0rOv5lyUAtAcrVuS+ANVaumV8WYLg577h/l1K6bGPdEqPSLLz+vnuZ3zjXsHzK+zDe2y0utD/+RrXFyfRFTL+7AJhHPE6igQQEZAywjaGLqI7IPXpCsRh9NmUZyCqQt0oMUkaXUcw1LPLzdcjnIUghfA72+7NFU5vqscAM0sMQNg7jzQ33XCPQU3usEFukKXTqioIKChbGshNbtkyE7FnNw+++SwfD8HppRTYYCy3VAf5e5kUaEJgXmx/CSRqt0MRkzajWB9AOjEQ6ytzqo1B/eZyqu+8Lla6zQELNF9j50ifHMbw7xtl+vUYQccpLFTVpDjtuJrVR1DT/gPFyZSpKXUhrtMnCtXigxXOLeAb5usK5pFHqKSmX3uR0dL5d2nGzhH6tj7kpDCfQBFfTSbEL25d+ZiJKFDa1y/VQ4XPhgsPg2kwpqwJ9niKBdRCT5bYhVn17oNwyJP/dy3ZW1GPNhiUqF5KERLOi9H0W85zeiT1tkWeFntOxFOhBQt3DSQ8Z0CaZPdVP/8nZjISU7X3sEdeMbcpDXlX/Bp7F42jgS/Jq+6YFoQUpzoqe4Z+3kESJOCmMRK3Pl+H1B48TkwUEE/xQ8eBd1S2+GsrU+HOnWUE1CJB5HcmZFCg=}
